# Generated by Django 4.1.4 on 2022-12-28 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat',
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
    ]
