# Generated by Django 4.1.4 on 2022-12-29 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='subproducts/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subproducts', to='shop.product')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='subproduct',
            index=models.Index(fields=['id', 'slug'], name='shop_subpro_id_2b8819_idx'),
        ),
        migrations.AddIndex(
            model_name='subproduct',
            index=models.Index(fields=['name'], name='shop_subpro_name_05fe15_idx'),
        ),
        migrations.AddIndex(
            model_name='subproduct',
            index=models.Index(fields=['-created'], name='shop_subpro_created_3acada_idx'),
        ),
    ]
