# Generated by Django 4.1.4 on 2022-12-30 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_subproduct_image_alter_subproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproduct',
            name='image',
            field=models.ImageField(blank=True, upload_to='subproducts/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subproducts', to='shop.product'),
        ),
    ]
